language: rust
sudo: required
services:
- docker
rust:
- nightly
- 1.31.0
before_install:
- sudo apt-get update -qq
- sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-ce
- sudo wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m`
- sudo chmod 0755 /usr/local/bin/docker-compose
script:
- cargo test
